### ISSUE TITLE
getting output of the detections

### ISSUE THREAD

**Issue by FereshtehFeiz** [Asadullah-Dal17/Eyes-Position-Estimator-Mediapipe#4]
Hello, thank you for this work, is it possible to have the output of the real time blink and gaze position on the csv or txt format for each frame? 
or help me to have such an output. 

Thank you

**Comment by Asadullah-Dal17** [comment]
You can write the ouput of each frame in csv file here https://www.pythontutorial.net/python-basics/python-write-csv-file/
