### ISSUE TITLE
give input video

### ISSUE THREAD

**Issue by FereshtehFeiz** [Asadullah-Dal17/Eyes-Position-Estimator-Mediapipe#5]
Hello, 
How I can change the code in the way to give my own recorded video as an input, instead of the real time webcam camera? 
Thank you

**Comment by Asadullah-Dal17** [comment]
Yeah, you can just provide a source video path instead of webcam index

**Comment by FereshtehFeiz** [comment]
Thank you, I did it with video= cv2.VideoCapture('VIDEO_PATH')
